#!/bin/sh

NUM="${2:-5}"

PULSE=true

if [ "$PULSE" = true ]; then
    toggle() { pulsemixer --toggle-mute ;}
    mute() { pulsemixer --mute ;}
    up() { pulsemixer --change-volume +"$NUM" ;}
    down() { pulsemixer --change-volume -"$NUM" ;}
else
    toggle() { amixer sset Master toggle ;}
    mute() { amixer sset Master mute ;}
    up() { amixer sset Master "$NUM"%+ ;}
    down() { amixer sset Master "$NUM"%- ;}
fi

case $1 in
    toggle) amixer sset Master toggle ;;
    mute) amixer sset Master mute ;;
    up) amixer sset Master "$NUM"%+ ;;
    down) amixer sset Master "$NUM"%- ;;
esac

pkill -RTMIN+14 dwmblocks
