#!/usr/bin/env sh

pdf_reduce() {
    gs -sDEVICE=pdfwrite \
        -dCompatibilityLevel=1.4 \
        -dPDFSETTINGS=/ebook \
        -dNOPAUSE -dQUIET -dBATCH \
        -sOutputFile="$2" "$1"
}

for f in *pdf ; do
    echo $f
    pdf_reduce "${f}" "${f}.smaller.pdf"
done
